# Generated by Django 5.1.2 on 2025-02-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_twofactorauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorauth',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
