# Generated by Django 5.1.2 on 2025-02-04 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_twofactorauth_device_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwoFactorAuth',
            new_name='DeviceVerifyOTP',
        ),
    ]
