# Generated by Django 5.1.2 on 2025-03-28 18:33

import django.core.validators
import django.db.models.deletion
import subscriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_limit', models.IntegerField(default=20)),
                ('device_limit', models.IntegerField(default=1)),
                ('duration_days', models.IntegerField(default=14)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('level', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('device_name', models.CharField(max_length=100)),
                ('system_info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20, null=True)),
                ('plan_status', models.CharField(default='inactive', max_length=20)),
                ('emails_sent', models.IntegerField(default=0)),
                ('email_limit', models.IntegerField(default=0)),
                ('phonepe_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('plan_expiration_date', models.DateTimeField(blank=True, default=subscriptions.models.get_trial_expiration_date, null=True)),
                ('pending_plan_id', models.IntegerField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid mobile number.')])),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
