# Generated by Django 5.1.2 on 2025-01-29 23:12

import subscriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0019_alter_userprofile_plan_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_plan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phonepe_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='email_limit',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_expiration_date',
            field=models.DateTimeField(blank=True, default=subscriptions.models.get_trial_expiration_date, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(blank=True, choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Elite', 'Elite')], max_length=20, null=True),
        ),
    ]
