# Generated by Django 5.1.2 on 2025-02-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0022_userprofile_is_2fa_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='moblie',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
