# Generated by Django 5.1.2 on 2025-02-11 17:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0023_userprofile_moblie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='moblie',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', message='Enter a valid mobile number.')]),
        ),
    ]
