# Generated by Django 5.1.2 on 2025-02-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0024_remove_userprofile_moblie_userprofile_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='razorpay_payment_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_limit',
            field=models.IntegerField(default=0),
        ),
    ]
