# Generated by Django 5.1.2 on 2025-02-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0025_remove_userprofile_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='level',
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
