# Generated by Django 5.1.2 on 2025-02-17 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0026_plan_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='level',
            field=models.IntegerField(),
        ),
    ]
