# Generated by Django 5.1.2 on 2025-03-27 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, help_text='Email of the unsubscribed contact', max_length=254, null=True)),
                ('contact_file_name', models.CharField(blank=True, help_text='Name of the contact file', max_length=255, null=True)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined name for the contact file', max_length=255)),
                ('file', models.FileField(blank=True, help_text='Uploaded contact file', null=True, upload_to='contact_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='Data of the CSV row')),
                ('contact_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='email_sender.contactfile')),
            ],
        ),
        migrations.CreateModel(
            name='EmailStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('smtp_server', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('use_tls', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='User-defined name for the Subject file', max_length=255)),
                ('data', models.JSONField(default=list, help_text='Data of the CSV row')),
                ('file', models.FileField(blank=True, help_text='Subject file', null=True, upload_to='subject_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, help_text='Key for Template', max_length=255, null=True)),
                ('file_url', models.URLField(max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=255)),
                ('delay_seconds', models.PositiveIntegerField(help_text='Delay between emails in seconds')),
                ('display_name', models.CharField(blank=True, help_text='Display name for the sender', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the campaign was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the campaign was last updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('contact_list', models.ForeignKey(help_text='Contact list associated with the campaign', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='email_sender.contactfile')),
                ('smtp_servers', models.ManyToManyField(help_text='SMTP servers used for the campaign', related_name='campaigns', to='email_sender.smtpserver')),
                ('subject_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sender.subjectfile')),
                ('uploaded_file', models.ForeignKey(blank=True, help_text='Template Associated with the campaign', null=True, on_delete=django.db.models.deletion.CASCADE, to='email_sender.uploadedfile')),
            ],
        ),
    ]
