# Generated by Django 5.1.2 on 2025-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0035_unsubscribed_contactfile_contact_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='key',
            field=models.CharField(blank=True, help_text='Key for Template', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
