# Generated by Django 5.1.2 on 2025-02-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0038_remove_campaign_subject_subjectfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectfile',
            name='data',
            field=models.JSONField(default=list, help_text='Data of the CSV row'),
        ),
    ]
