# Generated by Django 5.1.2 on 2025-02-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0039_subjectfile_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectfile',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
